services:
  # Django Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - db
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate --fake-initial &&
             python manage.py runserver 0.0.0.0:8000"

  # PostgreSQL Database
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=praxy_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql\data
      - ./database:/docker-entrypoint-initdb.d

  # React Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - backend


volumes:
  postgres_data:
