networks:
  moja-network:
    driver: bridge

services:
  # Django Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app # len raz!
    entrypoint: ["sh", "/app/entrypoint.sh"]
    networks:
      - moja-network

  # PostgreSQL Database
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=praxy_db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - moja-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - moja-network

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - moja-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - backend
    networks:
      - moja-network

volumes:
  postgres_data:
