# Generated by Django 5.2.7 on 2025-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='allow_password_grant',
            field=models.BooleanField(default=False, help_text='Allow this client to use the password grant (first-party only).'),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indicates if the client is public (PKCE required, no secret).'),
        ),
    ]
