# Generated by Django 5.2.7 on 2025-11-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_authorizationcode_code_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='service_user',
            field=models.ForeignKey(blank=True, help_text='Service account used for client_credentials grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_service_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
