# Generated by Django 5.2.7 on 2025-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_oauthclient_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='allow_private_jwt',
            field=models.BooleanField(default=False, help_text='Allow client_assertion (private_key_jwt) in token endpoint.'),
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='public_key',
            field=models.TextField(blank=True, help_text='PEM encoded public key for verifying client_assertion.', null=True),
        ),
    ]
