# Generated by Django 5.2.7 on 2026-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_oauthclient_allow_private_jwt_and_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
