type IconName =
  | "download"
  | "file-spreadsheet"
  | "file-text"
  | "filter"
  | "key-round"
  | "mail-check"
  | "upload"
  | "workflow"
  | "check-circle-2"
  | "info"
  | "alert-triangle"
  | "x"
  | "users"
  | "badge-check"
  | "shield"
  | "building-2"
  | "calendar-plus"
  | "loader-2"
  | "arrow-left"
  | "graduation-cap"
  | "globe"
  | "log-out"
  | "shield-check"
  | "refresh-cw"
  | "lock-keyhole"
  | "arrow-right"
  | "pencil"
  | "more-horizontal"
  | "calendar-days"
  | "chevron-right"
  | "chevron-left";

export default IconName;
