# Generated by Django 5.2.7 on 2026-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0002_add_forma_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaStavovPraxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stary_stav', models.CharField(blank=True, choices=[('vytvorena', 'Vytvorená'), ('potvrdena', 'Potvrdená'), ('zamietnuta', 'Zamietnutá'), ('schvalena', 'Schválená'), ('obhajena', 'Obhájená'), ('neobhajena', 'Neobhájená')], max_length=20, null=True)),
                ('novy_stav', models.CharField(choices=[('vytvorena', 'Vytvorená'), ('potvrdena', 'Potvrdená'), ('zamietnuta', 'Zamietnutá'), ('schvalena', 'Schválená'), ('obhajena', 'Obhájená'), ('neobhajena', 'Neobhájená')], max_length=20)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('zmena_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historia_stavov_praxe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('semester', models.CharField(choices=[('zimny', 'Zimný'), ('letny', 'Letný')], max_length=10)),
                ('datum_zaciatku', models.DateField()),
                ('datum_konca', models.DateField()),
                ('forma', models.CharField(choices=[('dohoda', 'Dohoda o odbornej praxi'), ('zamestnanie', 'Platené zamestnanie')], default='dohoda', max_length=20)),
                ('stav', models.CharField(choices=[('vytvorena', 'Vytvorená'), ('potvrdena', 'Potvrdená'), ('zamietnuta', 'Zamietnutá'), ('schvalena', 'Schválená'), ('obhajena', 'Obhájená'), ('neobhajena', 'Neobhájená')], default='vytvorena', max_length=20)),
                ('vytvorene_at', models.DateTimeField(auto_now_add=True)),
                ('zmenene_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'praxe',
                'managed': False,
            },
        ),
    ]
