# Generated by Django 5.2.7 on 2026-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_add_faktura_zamestnanie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_dokumentu', models.CharField(choices=[('dohoda', 'Dohoda'), ('zmluva', 'Zmluva'), ('zamestnanie', 'Pracovná zmluva'), ('vykaz', 'Výkaz'), ('faktura', 'Faktúra')], max_length=20)),
                ('subor_url', models.TextField()),
                ('stav_dokumentu', models.CharField(choices=[('nahrany', 'Nahraný'), ('potvrdeny', 'Potvrdený'), ('zamietnuty', 'Zamietnutý')], default='nahrany', max_length=20)),
                ('skontrolovane_at', models.DateTimeField(blank=True, null=True)),
                ('vytvorene_at', models.DateTimeField(auto_now_add=True)),
                ('zmenene_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dokumenty',
                'managed': False,
            },
        ),
    ]
